"""Generate shared Bresenham-prefix visibility branches; no runtime tree."""
import argparse
from pathlib import Path


def generate():
    nodes = [{"tile": None, "children": {}, "visible": [0] * 13}]
    for ty in range(13):
        for tx in range(13):
            if (tx - 6)**2 + (ty - 6)**2 > 36:
                continue
            x, y = 6, 6
            dx, dy = abs(tx - 6), abs(ty - 6)
            sx, sy = (1 if tx > 6 else -1), (1 if ty > 6 else -1)
            error, node = dx - dy, 0
            while (x, y) != (tx, ty):
                twice = 2 * error
                if twice > -dy:
                    error -= dy
                    x += sx
                if twice < dx:
                    error += dx
                    y += sy
                if (x, y) == (tx, ty):
                    break
                tile = (x, y)
                children = nodes[node]["children"]
                if tile not in children:
                    children[tile] = len(nodes)
                    nodes.append({"tile": tile, "children": {}, "visible": [0] * 13})
                node = children[tile]
            nodes[node]["visible"][ty] |= 1 << tx
    assert len(nodes) == 97
    lines = ["// Generated by tools/generate_ray_sight.py. Do not edit by hand.",
             "// Identical ordered ray prefixes share one fixed blocker test.",
             "#pragma once", "", "static_assert(MAX_LIGHT_RADIUS == 6, \"regenerate shared visibility for a new radius\");", "",
             "__attribute__((noinline)) void ray_sight(",
             "    const uint16_t opaque[13], uint16_t sight[13])", "{"]
    for row, mask in enumerate(nodes[0]["visible"]):
        lines.append(f"    sight[{row}] = 0x{mask:04x};")

    def emit(index, indent):
        node = nodes[index]
        x, y = node["tile"]
        pad = " " * indent
        lines.append(f"{pad}if(!(opaque[{y}] & 0x{1 << x:04x})) {{")
        for row, mask in enumerate(node["visible"]):
            if mask:
                lines.append(f"{pad}    sight[{row}] |= 0x{mask:04x};")
        # Use reverse construction order for stable generated output.
        for child in reversed(list(node["children"].values())):
            emit(child, indent + 4)
        lines.append(pad + "}")

    for child in reversed(list(nodes[0]["children"].values())):
        emit(child, 4)
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = Path(__file__).resolve().parents[1] / "src/ray_sight_generated.hpp"
    text = generate()
    if args.check:
        if output.read_text(encoding="utf-8") != text:
            raise SystemExit("Shared visibility header is stale; run tools/generate_ray_sight.py")
    else:
        output.write_text(text, encoding="utf-8")
