// Generated by tools/generate_ray_sight.py. Do not edit by hand.
// Identical ordered ray prefixes share one fixed blocker test.
#pragma once

static_assert(MAX_LIGHT_RADIUS == 6, "regenerate shared visibility for a new radius");

__attribute__((noinline)) void ray_sight(
    const uint16_t opaque[13], uint16_t sight[13])
{
    sight[0] = 0x0000;
    sight[1] = 0x0000;
    sight[2] = 0x0000;
    sight[3] = 0x0000;
    sight[4] = 0x0000;
    sight[5] = 0x00e0;
    sight[6] = 0x00e0;
    sight[7] = 0x00e0;
    sight[8] = 0x0000;
    sight[9] = 0x0000;
    sight[10] = 0x0000;
    sight[11] = 0x0000;
    sight[12] = 0x0000;
    if(!(opaque[7] & 0x0080)) {
        sight[8] |= 0x0100;
        if(!(opaque[8] & 0x0100)) {
            sight[9] |= 0x0200;
            if(!(opaque[9] & 0x0200)) {
                sight[10] |= 0x0400;
            }
        }
        if(!(opaque[8] & 0x0080)) {
            sight[9] |= 0x0100;
            if(!(opaque[9] & 0x0100)) {
                sight[10] |= 0x0200;
                if(!(opaque[10] & 0x0100)) {
                    sight[11] |= 0x0200;
                }
            }
        }
        if(!(opaque[7] & 0x0100)) {
            sight[8] |= 0x0200;
            if(!(opaque[8] & 0x0200)) {
                sight[9] |= 0x0400;
                if(!(opaque[8] & 0x0400)) {
                    sight[9] |= 0x0800;
                }
            }
        }
    }
    if(!(opaque[7] & 0x0040)) {
        sight[8] |= 0x00e0;
        if(!(opaque[8] & 0x0080)) {
            sight[9] |= 0x0080;
            if(!(opaque[9] & 0x0080)) {
                sight[10] |= 0x0100;
                if(!(opaque[10] & 0x0100)) {
                    sight[11] |= 0x0100;
                }
            }
        }
        if(!(opaque[8] & 0x0040)) {
            sight[9] |= 0x0040;
            if(!(opaque[9] & 0x0080)) {
                sight[10] |= 0x0080;
                if(!(opaque[10] & 0x0080)) {
                    sight[11] |= 0x0080;
                }
            }
            if(!(opaque[9] & 0x0040)) {
                sight[10] |= 0x0040;
                if(!(opaque[10] & 0x0040)) {
                    sight[11] |= 0x0040;
                    if(!(opaque[11] & 0x0040)) {
                        sight[12] |= 0x0040;
                    }
                }
            }
            if(!(opaque[9] & 0x0020)) {
                sight[10] |= 0x0020;
                if(!(opaque[10] & 0x0020)) {
                    sight[11] |= 0x0020;
                }
            }
        }
        if(!(opaque[8] & 0x0020)) {
            sight[9] |= 0x0020;
            if(!(opaque[9] & 0x0020)) {
                sight[10] |= 0x0010;
                if(!(opaque[10] & 0x0010)) {
                    sight[11] |= 0x0010;
                }
            }
        }
    }
    if(!(opaque[7] & 0x0020)) {
        sight[8] |= 0x0010;
        if(!(opaque[8] & 0x0020)) {
            sight[9] |= 0x0010;
            if(!(opaque[9] & 0x0010)) {
                sight[10] |= 0x0008;
                if(!(opaque[10] & 0x0010)) {
                    sight[11] |= 0x0008;
                }
            }
        }
        if(!(opaque[8] & 0x0010)) {
            sight[9] |= 0x0008;
            if(!(opaque[9] & 0x0008)) {
                sight[10] |= 0x0004;
            }
        }
        if(!(opaque[7] & 0x0010)) {
            sight[8] |= 0x0008;
            if(!(opaque[8] & 0x0008)) {
                sight[9] |= 0x0004;
                if(!(opaque[8] & 0x0004)) {
                    sight[9] |= 0x0002;
                }
            }
        }
    }
    if(!(opaque[6] & 0x0080)) {
        sight[5] |= 0x0100;
        sight[6] |= 0x0100;
        sight[7] |= 0x0100;
        if(!(opaque[7] & 0x0100)) {
            sight[7] |= 0x0200;
            if(!(opaque[7] & 0x0200)) {
                sight[8] |= 0x0400;
                if(!(opaque[8] & 0x0400)) {
                    sight[8] |= 0x0800;
                }
            }
        }
        if(!(opaque[6] & 0x0100)) {
            sight[6] |= 0x0200;
            if(!(opaque[7] & 0x0200)) {
                sight[7] |= 0x0400;
                if(!(opaque[7] & 0x0400)) {
                    sight[7] |= 0x0800;
                }
            }
            if(!(opaque[6] & 0x0200)) {
                sight[6] |= 0x0400;
                if(!(opaque[6] & 0x0400)) {
                    sight[6] |= 0x0800;
                    if(!(opaque[6] & 0x0800)) {
                        sight[6] |= 0x1000;
                    }
                }
            }
            if(!(opaque[5] & 0x0200)) {
                sight[5] |= 0x0400;
                if(!(opaque[5] & 0x0400)) {
                    sight[5] |= 0x0800;
                }
            }
        }
        if(!(opaque[5] & 0x0100)) {
            sight[5] |= 0x0200;
            if(!(opaque[5] & 0x0200)) {
                sight[4] |= 0x0400;
                if(!(opaque[4] & 0x0400)) {
                    sight[4] |= 0x0800;
                }
            }
        }
    }
    if(!(opaque[6] & 0x0020)) {
        sight[5] |= 0x0010;
        sight[6] |= 0x0010;
        sight[7] |= 0x0010;
        if(!(opaque[7] & 0x0010)) {
            sight[7] |= 0x0008;
            if(!(opaque[7] & 0x0008)) {
                sight[8] |= 0x0004;
                if(!(opaque[8] & 0x0004)) {
                    sight[8] |= 0x0002;
                }
            }
        }
        if(!(opaque[6] & 0x0010)) {
            sight[6] |= 0x0008;
            if(!(opaque[7] & 0x0008)) {
                sight[7] |= 0x0004;
                if(!(opaque[7] & 0x0004)) {
                    sight[7] |= 0x0002;
                }
            }
            if(!(opaque[6] & 0x0008)) {
                sight[6] |= 0x0004;
                if(!(opaque[6] & 0x0004)) {
                    sight[6] |= 0x0002;
                    if(!(opaque[6] & 0x0002)) {
                        sight[6] |= 0x0001;
                    }
                }
            }
            if(!(opaque[5] & 0x0008)) {
                sight[5] |= 0x0004;
                if(!(opaque[5] & 0x0004)) {
                    sight[5] |= 0x0002;
                }
            }
        }
        if(!(opaque[5] & 0x0010)) {
            sight[5] |= 0x0008;
            if(!(opaque[5] & 0x0008)) {
                sight[4] |= 0x0004;
                if(!(opaque[4] & 0x0004)) {
                    sight[4] |= 0x0002;
                }
            }
        }
    }
    if(!(opaque[5] & 0x0080)) {
        sight[4] |= 0x0100;
        if(!(opaque[5] & 0x0100)) {
            sight[4] |= 0x0200;
            if(!(opaque[4] & 0x0200)) {
                sight[3] |= 0x0400;
                if(!(opaque[4] & 0x0400)) {
                    sight[3] |= 0x0800;
                }
            }
        }
        if(!(opaque[4] & 0x0100)) {
            sight[3] |= 0x0200;
            if(!(opaque[3] & 0x0200)) {
                sight[2] |= 0x0400;
            }
        }
        if(!(opaque[4] & 0x0080)) {
            sight[3] |= 0x0100;
            if(!(opaque[3] & 0x0100)) {
                sight[2] |= 0x0200;
                if(!(opaque[2] & 0x0100)) {
                    sight[1] |= 0x0200;
                }
            }
        }
    }
    if(!(opaque[5] & 0x0020)) {
        sight[4] |= 0x0010;
        if(!(opaque[5] & 0x0010)) {
            sight[4] |= 0x0008;
            if(!(opaque[4] & 0x0008)) {
                sight[3] |= 0x0004;
                if(!(opaque[4] & 0x0004)) {
                    sight[3] |= 0x0002;
                }
            }
        }
        if(!(opaque[4] & 0x0010)) {
            sight[3] |= 0x0008;
            if(!(opaque[3] & 0x0008)) {
                sight[2] |= 0x0004;
            }
        }
        if(!(opaque[4] & 0x0020)) {
            sight[3] |= 0x0010;
            if(!(opaque[3] & 0x0010)) {
                sight[2] |= 0x0008;
                if(!(opaque[2] & 0x0010)) {
                    sight[1] |= 0x0008;
                }
            }
        }
    }
    if(!(opaque[5] & 0x0040)) {
        sight[4] |= 0x00e0;
        if(!(opaque[4] & 0x0080)) {
            sight[3] |= 0x0080;
            if(!(opaque[3] & 0x0080)) {
                sight[2] |= 0x0100;
                if(!(opaque[2] & 0x0100)) {
                    sight[1] |= 0x0100;
                }
            }
        }
        if(!(opaque[4] & 0x0020)) {
            sight[3] |= 0x0020;
            if(!(opaque[3] & 0x0020)) {
                sight[2] |= 0x0010;
                if(!(opaque[2] & 0x0010)) {
                    sight[1] |= 0x0010;
                }
            }
        }
        if(!(opaque[4] & 0x0040)) {
            sight[3] |= 0x0040;
            if(!(opaque[3] & 0x0080)) {
                sight[2] |= 0x0080;
                if(!(opaque[2] & 0x0080)) {
                    sight[1] |= 0x0080;
                }
            }
            if(!(opaque[3] & 0x0020)) {
                sight[2] |= 0x0020;
                if(!(opaque[2] & 0x0020)) {
                    sight[1] |= 0x0020;
                }
            }
            if(!(opaque[3] & 0x0040)) {
                sight[2] |= 0x0040;
                if(!(opaque[2] & 0x0040)) {
                    sight[1] |= 0x0040;
                    if(!(opaque[1] & 0x0040)) {
                        sight[0] |= 0x0040;
                    }
                }
            }
        }
    }
}
